"""add reports obligations assignments notification outbox

Revision ID: b8f81b9a3983
Revises: 2626bc6e1ede
Create Date: 2026-07-14 06:58:12.096511

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b8f81b9a3983'
down_revision: str | Sequence[str] | None = '2626bc6e1ede'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TYPE IF EXISTS outbox_event_kind CASCADE")
    op.execute("DROP TYPE IF EXISTS outbox_event_status CASCADE")
    op.execute("DROP TYPE IF EXISTS notification_status CASCADE")
    op.execute("DROP TYPE IF EXISTS daily_report_status CASCADE")
    op.execute("DROP TYPE IF EXISTS assignment_schedule_type CASCADE")
    op.execute("DROP TYPE IF EXISTS report_obligation_status CASCADE")
    op.execute("DROP TYPE IF EXISTS equipment_ownership CASCADE")
    op.create_table('outbox_events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('event_key', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.Enum('report_submitted', 'control_panel_refresh', name='outbox_event_kind'), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processing', 'done', 'failed', name='outbox_event_status'), nullable=False),
    sa.Column('attempts', sa.BigInteger(), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_key', name='uq_outbox_event_key')
    )
    op.create_table('notification_log',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('notification_key', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=True),
    sa.Column('report_date', sa.Date(), nullable=True),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'sent', 'failed', name='notification_status'), nullable=False),
    sa.Column('attempts', sa.BigInteger(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('external_message_id', sa.String(length=64), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['max_groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('notification_key', name='uq_notification_key')
    )
    op.create_table('daily_reports',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('responsible_user_id', sa.BigInteger(), nullable=False),
    sa.Column('object_id', sa.BigInteger(), nullable=False),
    sa.Column('stage_id', sa.BigInteger(), nullable=False),
    sa.Column('contractor_id', sa.BigInteger(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('staff_itr', sa.BigInteger(), nullable=False),
    sa.Column('staff_internal', sa.BigInteger(), nullable=False),
    sa.Column('staff_external', sa.BigInteger(), nullable=False),
    sa.Column('soil_export_m3', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('status', sa.Enum('submitted', name='daily_report_status'), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], ),
    sa.ForeignKeyConstraint(['object_id'], ['objects.id'], ),
    sa.ForeignKeyConstraint(['responsible_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['stages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_daily_report_idempotency_key')
    )
    op.create_table('responsible_object_assignments',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('object_id', sa.BigInteger(), nullable=False),
    sa.Column('active_from', sa.Date(), nullable=False),
    sa.Column('active_to', sa.Date(), nullable=False),
    sa.Column('schedule_type', sa.Enum('daily', 'weekdays', name='assignment_schedule_type'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['object_id'], ['objects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'object_id', name='uq_responsible_assignment')
    )
    op.create_table('report_equipment',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('report_id', sa.BigInteger(), nullable=False),
    sa.Column('equipment_type_id', sa.BigInteger(), nullable=False),
    sa.Column('equipment_name_snapshot', sa.String(length=255), nullable=False),
    sa.Column('ownership', sa.Enum('own', 'rented', 'contractor', name='equipment_ownership'), nullable=False),
    sa.Column('unit_id', sa.BigInteger(), nullable=False),
    sa.Column('unit_name_snapshot', sa.String(length=64), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['equipment_type_id'], ['equipment_types.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['daily_reports.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report_obligations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('assignment_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('object_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'submitted', 'late', 'missed', 'exempt', name='report_obligation_status'), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('report_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['responsible_object_assignments.id'], ),
    sa.ForeignKeyConstraint(['object_id'], ['objects.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['daily_reports.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_date', 'assignment_id', name='uq_obligation_date_assignment')
    )
    op.create_table('report_works',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('report_id', sa.BigInteger(), nullable=False),
    sa.Column('work_type_id', sa.BigInteger(), nullable=False),
    sa.Column('work_name_snapshot', sa.String(length=255), nullable=False),
    sa.Column('work_method_id', sa.BigInteger(), nullable=True),
    sa.Column('method_name_snapshot', sa.String(length=255), nullable=True),
    sa.Column('unit_id', sa.BigInteger(), nullable=False),
    sa.Column('unit_name_snapshot', sa.String(length=64), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['daily_reports.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.ForeignKeyConstraint(['work_method_id'], ['work_methods.id'], ),
    sa.ForeignKeyConstraint(['work_type_id'], ['work_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report_works')
    op.drop_table('report_obligations')
    op.drop_table('report_equipment')
    op.drop_table('responsible_object_assignments')
    op.drop_table('daily_reports')
    op.drop_table('notification_log')
    op.drop_table('outbox_events')
    # ### end Alembic commands ###
